# Generated by Django 4.0.5 on 2022-06-25 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale_management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=50, null=True)),
                ('contract_date', models.DateField(default=datetime.date(2022, 6, 25), null=True)),
                ('valid_from_date', models.DateField(default=datetime.date(2022, 6, 25), null=True)),
                ('valid_to_date', models.DateField(default=datetime.date(2022, 6, 25), null=True)),
                ('status_date', models.DateField(default=datetime.date(2022, 6, 25), null=True)),
                ('placement_time_in_prior_to_delivery', models.IntegerField(null=True)),
                ('delivery_time', models.DateTimeField(default=datetime.date(2022, 6, 25), null=True)),
                ('registration_document', models.CharField(max_length=100, null=True)),
                ('payment_method', models.CharField(max_length=100, null=True)),
                ('payment_due', models.IntegerField(null=True)),
                ('penalty_rate_for_late_payment', models.IntegerField(null=True)),
                ('bank_charges_related_to_payment', models.IntegerField(null=True)),
                ('delivery_point', models.CharField(max_length=500, null=True)),
                ('enquiry_for_goods_receipt', models.CharField(max_length=500, null=True)),
                ('enquiry_for_goods_return', models.CharField(max_length=500, null=True)),
                ('documents_to_be_delivered_with_each_delivery', models.CharField(max_length=500, null=True)),
                ('complaint_time_due_to_product_issue', models.IntegerField(null=True)),
                ('compensation_time', models.IntegerField(null=True)),
                ('support_fee_on_target_achivement', models.IntegerField(null=True)),
                ('support_fee_on_transportation', models.IntegerField(null=True)),
                ('support_fee_for_payment_due_date', models.IntegerField(null=True)),
                ('support_fee_for_new_pos', models.IntegerField(null=True)),
                ('support_fee_for_display', models.IntegerField(null=True)),
                ('support_fee_for_listing', models.IntegerField(null=True)),
                ('support_fee_for_advertising_and_birthday', models.IntegerField(null=True)),
                ('support_fee_for_product_creation', models.IntegerField(null=True)),
                ('method_of_support_fee_payment', models.CharField(max_length=100, null=True)),
                ('penalty_for_agreement_breach', models.IntegerField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sale_management.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=50, null=True)),
                ('quotation_date', models.DateField(default=datetime.date(2022, 6, 25), null=True)),
                ('status_date', models.DateField(default=datetime.date(2022, 6, 25), null=True)),
                ('quotation_remark', models.CharField(max_length=500, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sale_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price_vat', models.IntegerField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sale_management.product')),
                ('quotation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotation.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotation.status'),
        ),
        migrations.CreateModel(
            name='contract_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price_vat', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contract_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotation.contract')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sale_management.product')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotation.status'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sale_management.customer'),
        ),
    ]
