# Generated by Django 4.0.5 on 2022-06-28 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(default=datetime.date(2022, 6, 28), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.date(2022, 6, 28), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status_date',
            field=models.DateField(default=datetime.date(2022, 6, 28), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_from_date',
            field=models.DateField(default=datetime.date(2022, 6, 28), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='valid_to_date',
            field=models.DateField(default=datetime.date(2022, 6, 28), null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(default=datetime.date(2022, 6, 28), null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status_date',
            field=models.DateField(default=datetime.date(2022, 6, 28), null=True),
        ),
    ]
