# Generated by Django 4.0.5 on 2022-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
